### ISSUE TITLE
XamlCombine is not working with UWP/WinUI

### ISSUE THREAD

**Issue by ghost1372** [fluentribbon/XamlCombine#4]
Hi @batzen 
In UWP/WinUI we have different types that we can use in the ResourceDictionary for example:

`<ThemeShadow Name="theme"/>
`
or

```
<ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Dark">
...
        </ResourceDictionary>

        <ResourceDictionary x:Key="Light">
...
        </ResourceDictionary>

        <ResourceDictionary x:Key="HighContrast">
...
        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>
```

can you please update xamlcombine for supporting this?

**Comment by batzen** [comment]
Hi there. I forgot to add a deprecation notice to this repo.
Could you re-create your issue at https://github.com/batzen/XAMLTools? Sadly I can't transfer the issue to a different organisation on GitHub.

**Comment by ghost1372** [comment]
thank you
[i created a new issue](https://github.com/batzen/XAMLTools/issues/47)
